# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-11-12 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0008_auto_20210302_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderheader',
            name='fs_code',
            field=models.CharField(blank=True, db_column='FSCODE', max_length=10, null=True),
        ),
    ]
