# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-11-13 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0009_auto_20211112_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderheader',
            name='customer_reference_number',
            field=models.CharField(blank=True, db_column='CUSREFNO', max_length=150, null=True),
        ),
    ]
